# Site
name: "Wireless Hippie"
title: "Wireless Hippie"
description: "An online diary for a wireless hippie"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /index.html
google_analytics: 'UA-46278016-1'
disqus: 'https-wireless-hippie-github-io'
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  Mariana:
    name: Mariana Meireles
    display_name: Mariana Meireles
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: mariana@psychonaugirl.space
    web: https://psychonautgirl.space/about-me.html
    twitter: https://twitter.com/mari_meir
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
